name: Push 6088
on:
  # schedule:
  #   - cron: '00 20 * * *'
  push:
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - 'LICENSE'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:6088"
          push: true
          platforms: linux/amd64
          tags: sliamb/opbuilder:6088
      - name: build
        run: sh ./6088/build.sh
      - name: Upload bin
        uses: actions/upload-artifact@v4
        with:
            name: 6088bin.tar.gz
            path: 6088bin.tar.gz