name: push make 6088 docker bin
on:
  # schedule:
  #   - cron: '00 20 * * *'
  push:
    paths:
        - '6088/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: install 7zip
        run: sudo apt-get -qq -y install p7zip-full
      - name: Maximize Build Space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 5120
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:6088"
          push: true
          platforms: linux/amd64
          tags: sliamb/opbuilder:6088
      - name: build
        run: docker run --name 6088 -v$(pwd):/src/bin/targets/ sliamb/opbuilder:6088
      - name: pack
        run: ls -lha ./mediatek/mt7986/* && cp ./mediatek/mt7986/*sysupgrade.bin 6088.bin && 7z a -t7z -mx=9 6088.7z 6088.bin
      - name: Upload bin
        uses: actions/upload-artifact@v4
        with:
            name: 6088.7z
            path: 6088.7z