name: push make 6088ib docker bin
on:
  # schedule:
  #   - cron: '00 20 * * *'
  push:
    paths:
        - '6088ib/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: install 7zip
        run: sudo apt-get -qq -y install p7zip-full
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:6088ib"
          push: true
          platforms: linux/amd64
          tags: sliamb/opbuilder:6088ib