name: push make ax6 docker bin
on:
  # schedule:
  #   - cron: '00 20 * * *'
  push:
    paths:
        - 'ax6/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: install 7zip
        run: sudo apt-get -qq -y install p7zip-full
      - name: Pure env
        run: rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:ax6"
          push: true
          platforms: linux/amd64
          tags: sliamb/opbuilder:ax6
      - name: build
        run: docker run --name ax6 -v$(pwd):/src/bin/targets/ sliamb/opbuilder:ax6
      - name: pack
        run: ls -lah ./qualcommax/ipq807x/* && cp ./qualcommax/ipq807x/*sysupgrade.bin ax6.bin && 7z a -t7z -mx=9 ax6.7z ax6.bin
      - name: Upload bin
        uses: actions/upload-artifact@v4
        with:
            name: ax6.7z
            path: ax6.7z