name: push make ax6 docker bin
on:
  # schedule:
  #   - cron: '00 20 * * *'
  push:
    paths:
        - 'ax6/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: install 7zip
        run: sudo apt-get -qq -y install p7zip-full
      - name: Maximize Build Space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 5120
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - name: Free Disk Space
        uses: endersonmenezes/free-disk-space@main
        with:
          remove_android: true
          remove_dotnet: true
          remove_haskell: true
          remove_tool_cache: true
          remove_swap: true
          remove_packages: "android* azure* clang* dotnet* firefox* ghc* golang* google* libclang* libgl1* lld* llvm* \
            microsoft* mongodb* mono* mysql* nodejs* openjdk* php* postgresql* powershell* snap* temurin* yarn* zulu*"
          remove_packages_one_command: true
          remove_folders: "/etc/apt/sources.list.d* /etc/mono* /etc/mysql* /usr/include/linux/android* /usr/lib/llvm* /usr/lib/mono* \
            /usr/local/lib/android* /usr/local/lib/node_modules* /usr/local/share/chromium* /usr/local/share/powershell* \
            /usr/local/share/vcpkg/ports/azure* /usr/local/share/vcpkg/ports/google* /usr/local/share/vcpkg/ports/libpq/android* \
            /usr/local/share/vcpkg/ports/llvm* /usr/local/share/vcpkg/ports/mysql* /usr/local/share/vcpkg/ports/snap* \
            /usr/share/azure* /usr/share/dotnet* /usr/share/glade* /usr/share/miniconda* /usr/share/php* /usr/share/swift \
            /var/lib/mysql* /var/log/azure*"
          testing: false
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:ax6"
          push: true
          platforms: linux/amd64
          tags: sliamb/opbuilder:ax6
      - name: build
        run: docker run --name ax6 -v$(pwd):/src/bin/targets/ sliamb/opbuilder:ax6
      - name: pack
        run: ls -lah ./qualcommax/ipq807x/* && cp ./qualcommax/ipq807x/*sysupgrade.bin ax6.bin && 7z a -t7z -mx=9 ax6.7z ax6.bin
      - name: Upload bin
        uses: actions/upload-artifact@v4
        with:
            name: ax6.7z
            path: ax6.7z