name: make 6088
on:
  # schedule:
  #   - cron: '00 20 * * *'
  push:
    paths:
        - '6088/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build
        run: docker run --name 6088 -it -v$(pwd):/src/bin/targets/ sliamb/opbuilder:6088 make -j4 V=S
      - name: pack
        run: tar -czvf 6088bin.tar.gz ./mediatek/mt7986
      - name: Upload bin
        uses: actions/upload-artifact@v4
        with:
            name: 6088bin.tar.gz
            path: 6088bin.tar.gz